check-leaks: true
color: true
extension:
  - 'js'
file:
  - './test/es/CoreObject-test.js'
  - './test/es/MetaObject-test.js'
  - './test/es/mixins/StateMachineMixin-test.js'
  - './test/es/statemachine/Event-test.js'
  - './test/es/statemachine/State-test.js'
  - './test/es/statemachine/StateMachine-test.js'
  - './test/es/statemachine/Transition-test.js'
  - './test/es/utils/filter-test.js'
  - './test/es/utils/forEach-test.js'
  - './test/es/utils/jsonStringify-test.js'
  - './test/es/utils/map-test.js'
  - './test/patternes/command/Command-test.js'
  # - './test/patternes/command/SimpleCommand-test.js'
  # - './test/patternes/command/MacroCommand-test.js'
  - './test/patternes/facade/Facade-test.js'
  - './test/patternes/core/Controller-test.js'
  - './test/patternes/core/Model-test.js'
  - './test/patternes/core/View-test.js'
  - './test/patternes/mediator/Mediator-test.js'
  - './test/patternes/proxy/Proxy-test.js'
  - './test/patternes/observer/Notification-test.js'
  - './test/patternes/observer/Notifier-test.js'
  - './test/patternes/observer/Observer-test.js'
  - './test/pipes/Filter-test.js'
  - './test/pipes/FilterControlMessage-test.js'
  - './test/pipes/Junction-test.js'
  - './test/pipes/JunctionMediator-test.js'
  - './test/pipes/LineControlMessage-test.js'
  - './test/pipes/Line-test.js'
  - './test/pipes/LogFilterMessage-test.js'
  - './test/pipes/LogMessage-test.js'
  - './test/pipes/Pipe-test.js'
  - './test/pipes/PipeAwareModule-test.js'
  - './test/pipes/PipeListener-test.js'
  - './test/pipes/PipeMessage-test.js'
  - './test/pipes/TeeMerge-test.js'
  - './test/pipes/TeeSplit-test.js'
  - './test/leanes/data_mapper/ArrayTransform-test.js'
  - './test/leanes/data_mapper/BooleanTransform-test.js'
  - './test/leanes/data_mapper/DateTransform-test.js'
  - './test/leanes/data_mapper/NumberTransform-test.js'
  - './test/leanes/data_mapper/Objectizer-test.js'
  - './test/leanes/data_mapper/ObjectTransform-test.js'
  - './test/leanes/data_mapper/StringTransform-test.js'
  - './test/leanes/data_mapper/Transform-test.js'
  - './test/leanes/data_mapper/Serializer-test.js'
  - './test/leanes/data_mapper/Queue-test.js'
  - './test/leanes/data_mapper/Record-test.js'
  - './test/leanes/data_mapper/Migration-test.js'
  - './test/leanes/facade/Application-test.js'
  - './test/leanes/iterator/Cursor-test.js'
  - './test/leanes/mixins/GenerateUuidMixin-test.js'
  - './test/leanes/mixins/ConfigurableMixin-test.js'
  - './test/leanes/mixins/MemoryConfigurationMixin-test.js'
  - './test/leanes/mixins/LoggingJunctionMixin-test.js'
  - './test/leanes/mixins/DelayableMixin-test.js'
  - './test/leanes/mixins/GenerateAutoincrementIdMixin-test.js'
  - './test/leanes/mixins/HttpSerializerMixin-test.js'
  - './test/leanes/mixins/IterableMixin-test.js'
  - './test/leanes/mixins/QueryableResourceMixin-test.js'
  - './test/leanes/mixins/QueryableCollectionMixin-test.js'
  - './test/leanes/mixins/HttpCollectionMixin-test.js'
  - './test/leanes/mixins/ThinHttpCollectionMixin-test.js'
  - './test/leanes/mixins/MemoryResqueMixin-test.js'
  - './test/leanes/mixins/RelationsMixin-test.js'
  - './test/leanes/mixins/MemoryExecutorMixin-test.js'
  - './test/leanes/mixins/MemoryMigrationMixin-test.js'
  - './test/leanes/query_object/Query-test.js'
  - './test/leanes/proxy/Configuration-test.js'
  - './test/leanes/proxy/Router-test.js'
  - './test/leanes/proxy/Collection-test.js'
  - './test/leanes/proxy/ResourceRenderer-test.js'
  - './test/leanes/proxy/Resque-test.js'
  - './test/leanes/mediator/Switch-test.js' # TODO: needs to move http server from Switch to external mixin
  - './test/leanes/switch/Response-test.js'
  - './test/leanes/switch/Request-test.js'
  - './test/leanes/switch/Context-test.js'
  - './test/leanes/command/DelayedJobScript-test.js'
  - './test/leanes/command/LogMessageCommand-test.js'
  - './test/leanes/command/Script-test.js'
  - './test/leanes/command/Resource-test.js'
  - './test/es/decorators/method-test.js'
  - './test/es/decorators/property-test.js'
  - './test/es/decorators/util-test.js'
  - './test/es/decorators/nameBy-test.js'
  - './test/es/decorators/machine-test.js'
  - './test/es/decorators/mixin-test.js'
  - './test/es/decorators/decorator-test.js'
  - './test/es/decorators/partOf-test.js'
  - './test/es/decorators/resolver-test.js'
  - './test/es/decorators/initializeMixin-test.js'
  - './test/es/decorators/meta-test.js'
  - './test/es/decorators/initialize-test.js'
  - './test/es/decorators/constant-test.js'
  - './test/es/decorators/chains-test.js'
  - './test/es/decorators/freeze-test.js'
  - './test/leanes/decorators/action-test.js'
  - './test/leanes/decorators/attribute-test.js'
  - './test/leanes/decorators/computed-test.js'
  - './test/leanes/mixins/SchemaModuleMixin-test.js' # TODO: needs corrections in SchemaModuleMixin
  - './test/leanes/command/MigrateCommand-test.js'
  - './test/leanes/command/RollbackCommand-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
require: '@babel/register'
# spec: 'test/**/**/*-test.js'
watch: true
