version: '3.5'
services:
  leanes:
    build: .
    container_name: leanes
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ENV=production
      - APP_PATH=${APP_PATH}
    volumes:
      - ${APP_PATH}:/usr/src/leanes
      - ${APP_PATH}/.bash_history:/root/.bash_history
    networks:
      - common
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: 750m
networks:
  common:
    external:
      name: common
